/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as celevenTSol from "./CelevenT.sol";
export type { celevenTSol };
export type { Vault } from "./Vault";
